### ISSUE TITLE
I cannot start the MogiTableBot.v202 file

### ISSUE THREAD

**Issue by Gecko491** [9tarek/8DX-Mogi-Table-Bot#1]
Hello sorry to bother you. I tried to follow the guide, however when I try to open the programme I get this error screen (I will send pictures). Im not particularly experienced so I could be doing something wrong (and i don't know English very well). I would be very happy if you could help me. Thanks.
![Screenshot (320)](https://github.com/user-attachments/assets/7556fb12-a6b0-463d-b67a-93fbaca8ec9c)
![Screenshot (321)](https://github.com/user-attachments/assets/51ab9fd4-ca8f-486b-8a39-ff283fa36310)

**Comment by 9tarek** [comment]
hi,
can you copy paste the error message please

**Comment by 9tarek** [comment]
Sadly after an hour of trying, I was not able to recreate the error, nor do i know why it occurs to you, because other pcs handle it fine. My only idea for a fix is download the chromedriver from [here](https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.70/win64/chromedriver-win64.zip).
Unzip it and put the chromedriver.exe file in the same folder as MogiTableBot.v202.exe.
Let me know if this resolved the issue

**Comment by Gecko491** [comment]
> hi, can you copy paste the error message please

sure:

Traceback (most recent call last):
  File "selenium\webdriver\common\driver_finder.py", line 71, in _binary_paths
ValueError: The driver path is not a valid file: C:\windows\system32\chromedriver.exe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "source.py", line 1106, in <module>
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "selenium\webdriver\chrome\webdriver.py", line 45, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 50, in __init__
  File "selenium\webdriver\common\driver_finder.py", line 47, in get_browser_path
  File "selenium\webdriver\common\driver_finder.py", line 78, in _binary_paths
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by Gecko491** [comment]
> Sadly after an hour of trying, I was not able to recreate the error, nor do i know why it occurs to you, because other pcs handle it fine. My only idea for a fix is download the chromedriver from [here](https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.70/win64/chromedriver-win64.zip). Unzip it and put the chromedriver.exe file in the same folder as MogiTableBot.v202.exe. Let me know if this resolved the issue

I tried but could not solve the problem. I don't know whether Windows Defender can somehow cause problems. I will try to see if any of my friends will be able to download it. Please consider making a mini tutorial video on youtube in the future. Thanks anyway for trying to help me, if there's any news please update me.

**Comment by 9tarek** [comment]
just to check something real quick, if you go to your C drive, -> Users, -> your user, -> .cache, is there a folder named selenium? If so, click on it and let me know if the chromedriver folder is there. Because the problem is, for some reason it tries to load the chromedriver from a folder, where it cleary shouldnt be.

**Comment by Gecko491** [comment]
> just to check something real quick, if you go to your C drive, -> Users, -> your user, -> .cache, is there a folder named selenium? If so, click on it and let me know if the chromedriver folder is there. Because the problem is, for some reason it tries to load the chromedriver from a folder, where it cleary shouldnt be.

Nop, the chromedriver folder is not there... inside the selenium folder I only have a file called ‘se-metadata JSON file’ but I think its a file that has nothing to do with this.

**Comment by 9tarek** [comment]
try [this](https://drive.google.com/file/d/1VA-AAK6aI7k-jMRrMrnZisT0i80-LrZo/view?usp=drive_link)
make sure you have chrome installed

**Comment by 9tarek** [comment]
does it work?
